
hparams:
  model_name_or_path: "/prj/doctoral_letters/PETGUI/med_bert_local"
  seed: 42
  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  num_train_epochs: 50
  batch_size: 16 # Smaller default for single GPU
  eval_steps: 1000
  save_steps: 100
  patience: 3
  fp16: False
  gradient_accumulation_steps: 1
  use_stratified_split: True
  use_class_weights: True

xai:
  enabled: true
  shap_num_background: 20      # number of background texts for SHAP
  shap_num_samples: 40         # number of samples to explain with SHAP text plots
  lime_num_samples: 10         # number of samples to explain with LIME
  max_tokens_for_xai: 512      # truncate to this many tokens for speed
  seed: 42
